name: C/C++ CI

on:
  push:
    branches: [ 15399-&-15035 ]
  pull_request:
    branches: [ 15399-&-15035 ]

jobs:
  build:

    runs-on: ubuntu-16.04

    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
    - name: compile
      run : ./build.sh
